var backendUrl = 'https://private-d82ca-hackathlon.apiary-mock.com/';
var surveyUrl = backendUrl + "survey";
var searchUrl = backendUrl + 'byTag';
var searchPromotorUrl =  backendUrl + 'byPromotorId/'; // +id
var searchPromotorArchiveUrl =  backendUrl + 'byPromotorIdArchive/'; // +id
var tagUrl =  backendUrl + 'search';
var profileUrl = backendUrl + 'promotor/'; // +id
var reviewUrl = backendUrl + 'promotor/praca/'; // +id
var saveReviewUrl = backendUrl + 'promotor/praca';